<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class GeneratePermissionTypes extends Command
{
    protected $signature = 'permissions:types';

    protected $description = 'Generate TypeScript types for permissions from config';

    public function handle(): int
    {
        $permissions = config('permissions.permissions', []);
        $roles = config('permissions.roles', []);

        $content = $this->generateTypesContent($permissions, $roles);

        $path = resource_path('js/types/permissions.ts');
        File::put($path, $content);

        $this->info("Generated: {$path}");

        return self::SUCCESS;
    }

    private function generateTypesContent(array $permissions, array $roles): string
    {
        $permissionUnion = implode(' | ', array_map(
            fn ($p) => "'{$p}'",
            $permissions,
        ));

        $roleKeys = array_keys($roles);
        $roleUnion = implode(' | ', array_map(
            fn ($r) => "'{$r}'",
            $roleKeys,
        ));

        return <<<TYPES
// Auto-generated by: php artisan permissions:types
// Do not edit manually

export type Permission =
    | '*'
    | {$permissionUnion};

export type WorkspaceRole =
    | {$roleUnion};

export type ProjectRole =
    | 'lead'
    | 'manager'
    | 'developer'
    | 'qa'
    | 'member';

export const WORKSPACE_PERMISSIONS: Permission[] = [
{$this->indentPermissions($permissions)}
];

export const ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
{$this->indentRoles($roles)}
};

export function hasPermission(
    permissions: Permission[],
    required: Permission,
): boolean {
    return permissions.includes('*') || permissions.includes(required);
}

export function hasWorkspacePermission(
    role: WorkspaceRole,
    permission: Permission,
): boolean {
    const perms = ROLE_PERMISSIONS[role];
    if (!perms) return false;
    return perms.includes('*') || perms.includes(permission);
}
TYPES;
    }

    private function indentPermissions(array $permissions): string
    {
        return implode(",\n", array_map(
            fn ($p) => "    '{$p}'",
            $permissions,
        ));
    }

    private function indentRoles(array $roles): string
    {
        $lines = [];
        $permissions = config('permissions.permissions', []);

        foreach ($roles as $role => $perms) {
            if ($perms === ['*'] || $perms === ['*', '*']) {
                $permLines = implode(', ', array_map(
                    fn ($p) => "'{$p}'",
                    $permissions,
                ));
                $lines[] = "    '{$role}': (['*', {$permLines}] as Permission[]),";
            } else {
                $permLines = implode(', ', array_map(
                    fn ($p) => "'{$p}'",
                    $perms,
                ));
                $lines[] = "    '{$role}': [{$permLines}],";
            }
        }

        return implode("\n", $lines);
    }
}
