// Auto-generated by: php artisan permissions:types
// Do not edit manually

export type Permission =
    | '*'
    | 'workspace.view'
    | 'workspace.edit'
    | 'workspace.delete'
    | 'workspace.manage-members'
    | 'workspace.manage-labels'
    | 'workspace.manage-task-types'
    | 'workspace.manage-priorities'
    | 'project.create'
    | 'project.view-any'
    | 'project.edit'
    | 'project.delete'
    | 'project.manage-members'
    | 'task.create'
    | 'task.edit-any'
    | 'task.edit-own'
    | 'task.assign'
    | 'task.view-own'
    | 'task.delete-any'
    | 'task.comment'
    | 'task.comment-own'
    | 'task.delete-comment-any'
    | 'epic.create'
    | 'epic.edit'
    | 'epic.delete'
    | 'sprint.create'
    | 'sprint.edit'
    | 'sprint.delete'
    | 'board.manage';

export type WorkspaceRole = 'owner' | 'admin' | 'manager' | 'member' | 'viewer' | 'guest';

export type ProjectRole = 'lead' | 'manager' | 'developer' | 'qa' | 'member' | 'viewer';

export const WORKSPACE_PERMISSIONS: Permission[] = [
    'workspace.view',
    'workspace.edit',
    'workspace.delete',
    'workspace.manage-members',
    'workspace.manage-labels',
    'workspace.manage-task-types',
    'workspace.manage-priorities',
    'project.create',
    'project.view-any',
    'project.edit',
    'project.delete',
    'project.manage-members',
    'task.create',
    'task.edit-any',
    'task.edit-own',
    'task.assign',
    'task.view-own',
    'task.delete-any',
    'task.comment',
    'task.comment-own',
    'task.delete-comment-any',
    'epic.create',
    'epic.edit',
    'epic.delete',
    'sprint.create',
    'sprint.edit',
    'sprint.delete',
    'board.manage',
];

export const ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
    owner: [
        '*',
        'workspace.view',
        'workspace.edit',
        'workspace.delete',
        'workspace.manage-members',
        'workspace.manage-labels',
        'workspace.manage-task-types',
        'workspace.manage-priorities',
        'project.create',
        'project.view-any',
        'project.edit',
        'project.delete',
        'project.manage-members',
        'task.create',
        'task.edit-any',
        'task.edit-own',
        'task.assign',
        'task.view-own',
        'task.delete-any',
        'task.comment',
        'task.comment-own',
        'task.delete-comment-any',
        'epic.create',
        'epic.edit',
        'epic.delete',
        'sprint.create',
        'sprint.edit',
        'sprint.delete',
        'board.manage',
    ] as Permission[],
    admin: [
        'workspace.view',
        'workspace.edit',
        'workspace.manage-members',
        'workspace.manage-labels',
        'workspace.manage-task-types',
        'workspace.manage-priorities',
        'project.create',
        'project.view-any',
        'project.edit',
        'project.delete',
        'project.manage-members',
        'task.create',
        'task.edit-any',
        'task.edit-own',
        'task.assign',
        'task.view-own',
        'task.delete-any',
        'task.comment',
        'task.comment-own',
        'task.delete-comment-any',
        'epic.create',
        'epic.edit',
        'epic.delete',
        'sprint.create',
        'sprint.edit',
        'sprint.delete',
        'board.manage',
    ],
    manager: [
        'workspace.view',
        'workspace.manage-labels',
        'workspace.manage-task-types',
        'workspace.manage-priorities',
        'project.create',
        'project.view-any',
        'project.edit',
        'project.manage-members',
        'task.create',
        'task.edit-any',
        'task.edit-own',
        'task.assign',
        'task.view-own',
        'task.delete-any',
        'task.comment',
        'task.comment-own',
        'task.delete-comment-any',
        'epic.create',
        'epic.edit',
        'epic.delete',
        'sprint.create',
        'sprint.edit',
        'sprint.delete',
        'board.manage',
    ],
    member: [
        'workspace.view',
        'project.view-any',
        'task.create',
        'task.edit-own',
        'task.assign',
        'task.comment',
    ],
    viewer: ['workspace.view', 'project.view-any'],
    guest: ['workspace.view', 'project.view-any', 'task.view-own', 'task.comment-own'],
};

export function hasPermission(
    permissions: Permission[],
    required: Permission,
): boolean {
    return permissions.includes('*') || permissions.includes(required);
}

export function hasWorkspacePermission(
    role: WorkspaceRole,
    permission: Permission,
): boolean {
    const perms = ROLE_PERMISSIONS[role];

    if (!perms) {
        return false;
    }

    return perms.includes('*') || perms.includes(permission);
}
