module.exports = {
    apps: [
        {
            name: 'qeerja-queue',
            script: 'artisan',
            cwd: '/var/www/taska.web.id',
            interpreter: 'php',
            args: ['queue:listen', '--tries=3', '--timeout=60', '--sleep=3'],
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'qeerja-reverb',
            script: 'artisan',
            cwd: '/var/www/taska.web.id',
            interpreter: 'php',
            args: ['reverb:start', '--host=0.0.0.0', '--port=6001', '--debug'],
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'qeerja-whatsapp',
            script: 'index.js',
            cwd: '/var/www/taska.web.id/whatsapp-gateway',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '500M',
            max_restarts: 10,
            restart_delay: 5000,
            exp_backoff_restart_delay: 100,
            env: {
                NODE_ENV: 'production',
                GATEWAY_PORT: 3001,
            },
        },
        {
            name: 'qeerja-realtime',
            script: 'index.js',
            cwd: '/var/www/taska.web.id/realtime-gateway',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            max_restarts: 10,
            restart_delay: 5000,
            env: {
                NODE_ENV: 'production',
                GATEWAY_PORT: 3002,
            },
        },
    ],
};
