# Laravel Queue Worker
[program:qeerja-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/taska.web.id/artisan queue:listen --tries=3 --timeout=60 --sleep=3
directory=/var/www/taska.web.id
autostart=true
autorestart=true
stopwaitsecs=3600
startretries=3
stopasgroup=true
killasgroup=true
user=deploy
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/taska.web.id/storage/logs/queue.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=5
