<?php

return [
    'permissions' => [
        'workspace.view',
        'workspace.edit',
        'workspace.delete',
        'workspace.manage-members',
        'workspace.manage-labels',
        'workspace.manage-task-types',
        'workspace.manage-priorities',
        'project.create',
        'project.view-any',
        'project.edit',
        'project.delete',
        'project.manage-members',
        'task.create',
        'task.edit-any',
        'task.delete-any',
        'task.comment',
        'task.delete-comment-any',
        'epic.create',
        'epic.edit',
        'epic.delete',
        'sprint.create',
        'sprint.edit',
        'sprint.delete',
        'board.manage',
    ],

    'roles' => [
        'owner' => ['*'],
        'admin' => [
            'workspace.view',
            'workspace.edit',
            'workspace.manage-members',
            'workspace.manage-labels',
            'workspace.manage-task-types',
            'workspace.manage-priorities',
            'project.create',
            'project.view-any',
            'project.edit',
            'project.delete',
            'project.manage-members',
            'task.create',
            'task.edit-any',
            'task.delete-any',
            'task.comment',
            'task.delete-comment-any',
            'epic.create',
            'epic.edit',
            'epic.delete',
            'sprint.create',
            'sprint.edit',
            'sprint.delete',
            'board.manage',
        ],
        'manager' => [
            'workspace.view',
            'workspace.manage-labels',
            'workspace.manage-task-types',
            'workspace.manage-priorities',
            'project.create',
            'project.view-any',
            'project.edit',
            'project.manage-members',
            'task.create',
            'task.edit-any',
            'task.delete-any',
            'task.comment',
            'task.delete-comment-any',
            'epic.create',
            'epic.edit',
            'epic.delete',
            'sprint.create',
            'sprint.edit',
            'sprint.delete',
            'board.manage',
        ],
        'member' => [
            'workspace.view',
            'project.view-any',
            'task.create',
            'task.comment',
        ],
        'viewer' => [
            'workspace.view',
            'project.view-any',
        ],
    ],
];
